const HOME_PAGE = "HOME_PAGE";
const SCHED_PAGE = "SCHED_PAGE";
const TASK_PAGE = "TASKS_PAGE";
const STATS_PAGE = "STATS_PAGE";
const SOCIAL_PAGE = "SOCIAL_PAGE";

const APP_PAGES = {
    TASK_PAGE,SCHED_PAGE,STATS_PAGE,SOCIAL_PAGE
};

const PAGE_BTN_ORDER= {
    TASK_PAGE: 0,
    SCHED_PAGE:1,
    STATS_PAGE:2,
    SOCIAL_PAGE:3
}


const CONSTANTS = [APP_PAGES,PAGE_BTN_ORDER];

export default CONSTANTS;