const HOME_PAGE = "HOME_PAGE";
const SCHED_PAGE = "SCHED_PAGE";
const TASK_PAGE = "TASKS_PAGE";
const STATS_PAGE = "STATS_PAGE";
const SOCIAL_PAGE = "SOCIAL_PAGE";

const APP_PAGES = {
    HOME_PAGE,SCHED_PAGE,TASK_PAGE,STATS_PAGE,SOCIAL_PAGE
};

export default APP_PAGES;